title: Cool Team Name
repository: cwp/gcd-quantum
shared_url: https://pages.github.azc.ext.hp.com/cwp/
assets_url: https://pages.github.azc.ext.hp.com/cwp/assets
dev_portal_url: https://developers.hp.com/hp-id
year: 2017
